[build]
  command = "bun run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-image-optim"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"

[[plugins]]
  package = "netlify-plugin-html-validate"

[[plugins]]
  package = "netlify-plugin-qawolf"

[[plugins]]
  package = "netlify-plugin-debug-cache"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "netlify-plugin-a11y"

[[plugins]]
  package = "netlify-plugin-is-website-vulnerable"

[[plugins]]
  package = "netlify-plugin-gridsome-cache"

[[plugins]]
  package = "netlify-plugin-no-more-404"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[[plugins]]
  package = "netlify-plugin-inline-source" 