name: CI & SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 2 * * *' # tous les jours à 2h du matin UTC

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    continue-on-error: true # Permet au workflow de continuer même si les tests échouent

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        continue-on-error: true

      - name: Install ts-node
        run: npm install --save-dev ts-node
        continue-on-error: true

      - name: Run Jest tests
        run: |
          if ! npm run test:jest; then
            echo "::warning::Jest tests failed but continuing..."
          fi
          if [ -f coverage/clover.xml ]; then
            cat coverage/clover.xml
          else
            echo "::warning::No coverage report found"
          fi
        continue-on-error: true

      - name: Build the app
        run: npm run build
        continue-on-error: true

      - name: Start preview server
        run: |
          npm run preview -- --port 5173 &
          sleep 5 # Attendre que le serveur démarre
        continue-on-error: true

      - name: Run Cypress tests
        run: |
          if ! CYPRESS_BASE_URL=http://localhost:5173 npm run test:cypress; then
            echo "::warning::Cypress tests failed but continuing..."
          fi
          if [ -f coverage/cypress/lcov.info ]; then
            cat coverage/cypress/lcov.info
          else
            echo "::warning::No Cypress coverage report found"
          fi
        continue-on-error: true

      - name: Merge coverage
        run: |
          if ! npm run coverage:merge; then
            echo "::warning::Coverage merge failed but continuing..."
          fi
          if [ -f coverage/lcov.info ]; then
            cat coverage/lcov.info
          else
            echo "::warning::No merged coverage report found"
          fi
        continue-on-error: true

      - name: Check SonarCloud Token
        run: |
          if [ -z "${{ secrets.Sonar_Token_GitHub_FlowyMusic }}" ]; then
            echo "::error::SonarCloud token is not set. Please add it to your repository secrets."
            exit 1
          fi
          echo "SonarCloud token is set"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.Sonar_Token_GitHub_FlowyMusic }}
        with:
          projectBaseDir: .
          args: |
            -Dsonar.projectKey=AsphalionY_FlowyMusic-main
            -Dsonar.organization=AsphalionY
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.token=${{ secrets.Sonar_Token_GitHub_FlowyMusic }}
        continue-on-error: true 