name: CI & SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 2 * * *' # tous les jours à 2h du matin UTC

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    continue-on-error: true # Permet au workflow de continuer même si les tests échouent

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install ts-node
        run: npm install --save-dev ts-node

      - name: Run Jest tests
        run: |
          npm run test:jest || echo "Tests failed but continuing..."
          cat coverage/clover.xml || true

      - name: Start Vite server
        run: npm run dev &
        env:
          CI: true

      - name: Wait for Vite server
        run: |
          timeout=60
          while ! curl -s http://localhost:5173 > /dev/null; do
            sleep 1
            timeout=$((timeout-1))
            if [ $timeout -le 0 ]; then
              echo "Timeout waiting for Vite server"
              exit 1
            fi
          done
          echo "Vite server is ready"

      - name: Run Cypress tests
        run: |
          npm run test:cypress || echo "Cypress tests failed but continuing..."
          cat coverage/cypress/lcov.info || true

      - name: Merge coverage
        run: |
          npm run coverage:merge || echo "Coverage merge failed but continuing..."
          cat coverage/lcov.info || true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=flowymusic
            -Dsonar.organization=flowymusic
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }} 